WINDOW_WIDTH = 800
WINDOW_HEIGHT = 600
FPS = 60
GRAVITY = 9.81
AIR_DENSITY = 1.225
MAX_THRUST = 20000
LIFT_COEFFICIENT = 0.3
DRAG_COEFFICIENT = 0.025

__all__ = ['WINDOW_WIDTH', 'WINDOW_HEIGHT', 'FPS', 'GRAVITY', 'AIR_DENSITY', 'MAX_THRUST', 'LIFT_COEFFICIENT', 'DRAG_COEFFICIENT']
